/**
 * The shared cross-SDK conformance vectors (generated by running the Go reference SDK):
 * `.claude/cross-sdk-checks/v3/vectors/*.json` in the SDKs' workspace. Every `expect` must be
 * reproduced, except the documented JS deviations below. Skipped when the vectors are not there
 * (the package is tested on its own).
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { QBitFlow } from '../src/client';
import { ZERO_TIME } from '../src/decode';
import { ServerError, ValidationError, WebhookSignatureError } from '../src/errors';
import { isUnknownEvent, isSubscriptionSession, parseEvent, verify } from '../src/webhooks';
import { invoke, probe } from './helpers/methods';
import { closeServers, type TestServer, testServer } from './helpers/server';

/* eslint-disable @typescript-eslint/no-explicit-any */

const DIR = join(__dirname, '..', '..', '.claude', 'cross-sdk-checks', 'v3', 'vectors');
const HAVE = existsSync(join(DIR, 'requests.json'));
const load = (name: string): any[] =>
	HAVE ? JSON.parse(readFileSync(join(DIR, `${name}.json`), 'utf8')).cases : [];
const d = HAVE ? describe : describe.skip;

/**
 * JS deviations: a path segment made only of dots can't be sent through `fetch` (the WHATWG URL
 * parser resolves `%2E%2E` as `..`), so the SDK refuses it with a ValidationError.
 */
const DOT_SEGMENT_CASES = new Set(['path: reference made of dots']);

const API_KEY = 'sk_test_conformance';
let server: TestServer;
let answer: { status: number; body: string } = { status: 200, body: '{}' };

beforeAll(async () => {
	server = await testServer((_req, res) => {
		res.writeHead(answer.status, { 'Content-Type': 'application/json' });
		res.end(answer.body);
	});
});
afterAll(closeServers);

const client = (): QBitFlow =>
	new QBitFlow({ apiKey: API_KEY, baseUrl: `${server.url}/v2`, maxRetries: 0 });

async function run(c: any): Promise<{ result?: unknown; error?: unknown }> {
	try {
		return { result: await invoke(client(), c.method, c.args ?? {}, c.options, c.client) };
	} catch (error) {
		return { error };
	}
}

function checkProbe(actual: unknown, p: any): void {
	const got = probe(actual, p.path);
	const where = `probe ${p.path}`;
	if (p.kind === 'time') {
		if (p.value === null) {
			expect([undefined, null, '', ZERO_TIME]).toContain(got);
		} else {
			expect(typeof got).toBe('string');
			expect({ where, at: Date.parse(got as string) }).toEqual({
				where,
				at: Date.parse(p.value),
			});
		}
		return;
	}
	if (p.optional && (p.value === '' || p.value === null) && got === undefined) return;
	if (p.value === null) {
		expect({ where, got: got ?? null }).toEqual({ where, got: null });
		return;
	}
	expect({ where, got }).toEqual({ where, got: p.value });
}

d('vectors: signature.json', () => {
	it.each(load('signature').map((c) => [c.name, c]))('%s', (_name, c: any) => {
		const body =
			c.rawBodyBase64 !== undefined ? Buffer.from(c.rawBodyBase64, 'base64') : c.rawBody;
		let outcome = 'ok';
		try {
			verify(body, c.header, c.secret, {
				tolerance: c.tolerance,
				now: new Date(c.now * 1000),
			});
		} catch (err) {
			if (err instanceof WebhookSignatureError) outcome = err.reason;
			else if (err instanceof ValidationError) outcome = 'validationError';
			else throw err;
		}
		expect(outcome).toBe(c.expect);
	});
});

d('vectors: events.json', () => {
	it.each(load('events').map((c) => [c.name, c]))('%s', (_name, c: any) => {
		let event: any;
		try {
			event = parseEvent(c.rawBody);
		} catch (err) {
			expect(c.expect.ok).toBe(false);
			expect(err).toBeInstanceOf(ValidationError);
			expect(c.expect.errorClass).toBe('ValidationError');
			return;
		}
		expect(c.expect.ok).toBe(true);
		expect(event.id).toBe(c.expect.id);
		expect(event.type).toBe(c.expect.type);
		expect(event.test).toBe(c.expect.test);
		expect(event.userUuid ?? '').toBe(c.expect.userUuid);
		expect(!isUnknownEvent(event)).toBe(c.expect.known);
		if (c.expect.dataShape) {
			expect(isSubscriptionSession(event.data) ? 'subscription' : 'payment').toBe(
				c.expect.dataShape
			);
		}
		for (const p of c.probes ?? []) checkProbe(event, p);
	});
});

d('vectors: validation.json', () => {
	it.each(load('validation').map((c) => [c.name, c]))('%s', async (_name, c: any) => {
		answer = { status: 200, body: '{}' };
		const before = server.recorded.length;
		const { error } = await run(c);
		const sent = server.recorded.length - before;
		if (c.expect === 'ok') {
			if (sent !== 1) throw error ?? new Error('no request sent');
			return;
		}
		expect(sent).toBe(0);
		if (c.expect.errorClass === 'WebhookSignatureError') {
			expect(error).toBeInstanceOf(WebhookSignatureError);
			expect((error as WebhookSignatureError).reason).toBe(c.expect.reason);
			return;
		}
		expect(error).toBeInstanceOf(ValidationError);
		const ve = error as ValidationError;
		expect(ve.status).toBeUndefined();
		expect([...new Set(ve.fieldErrors.map((f) => f.field))].sort()).toEqual(
			[...c.expect.fields].sort()
		);
	});
});

d('vectors: decoding.json', () => {
	it.each(load('decoding').map((c) => [c.name, c]))('%s', async (_name, c: any) => {
		answer = { status: c.status ?? 200, body: c.body };
		const { result, error } = await run(c);
		if (c.expect === 'serverError') {
			expect(error).toBeInstanceOf(ServerError);
			return;
		}
		if (error) throw error;
		for (const p of c.probes ?? []) checkProbe(result, p);
	});
});

function decodeSegment(s: string): string {
	return decodeURIComponent(s);
}

function decodeQuery(raw: string): Array<[string, string]> {
	if (raw === '') return [];
	return raw
		.split('&')
		.map((kv) => {
			const i = kv.indexOf('=');
			const dec = (s: string) => decodeURIComponent(s.replace(/\+/g, ' '));
			return [dec(i < 0 ? kv : kv.slice(0, i)), dec(i < 0 ? '' : kv.slice(i + 1))] as [
				string,
				string,
			];
		})
		.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
}

d('vectors: requests.json', () => {
	it.each(load('requests').map((c) => [c.name, c]))('%s', async (_name, c: any) => {
		answer = { status: 200, body: '{}' };
		const before = server.recorded.length;
		const { error } = await run(c);
		if (DOT_SEGMENT_CASES.has(c.name)) {
			expect(error).toBeInstanceOf(ValidationError);
			expect(server.recorded.length).toBe(before);
			return;
		}
		expect(server.recorded.length - before).toBe(1);
		const r = server.recorded[before];
		const want = c.request;
		expect(r.method).toBe(want.verb);

		expect(r.path.startsWith('/v2/')).toBe(true);
		const rawSegments = r.path.slice('/v2/'.length).split('/');
		expect(rawSegments.length).toBe(want.pathSegments.length);
		for (const s of rawSegments) expect(['.', '..']).not.toContain(s);
		expect(rawSegments.map(decodeSegment)).toEqual(want.pathSegments);

		expect(r.query).not.toContain('+');
		const got = decodeQuery(r.query);
		expect(got.map(([k]) => k)).toEqual(want.query.map((kv: [string, string]) => kv[0]));
		got.forEach(([k, v], i) => {
			const w = want.query[i][1];
			if (k === 'createdAfter' || k === 'createdBefore')
				expect(Date.parse(v)).toBe(Date.parse(w));
			else expect(v).toBe(w);
		});

		for (const [name, value] of Object.entries(want.headers as Record<string, string | null>)) {
			const actual = r.headers[name.toLowerCase()];
			if (value === null) expect({ name, actual }).toEqual({ name, actual: undefined });
			else if (value === '<uuid-v4>') {
				expect(actual).toMatch(
					/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
				);
			} else expect({ name, actual }).toEqual({ name, actual: value });
		}
		if (want.body === null) expect(r.body).toBe('');
		else expect(JSON.parse(r.body)).toEqual(want.body);
	});
});
