/**
 * Local webhook signature verification.
 *
 * The REFERENCE_VECTORS below were generated by the Go SDK, which canonicalises with the
 * same `encoding/json` the QBitFlow API itself uses. Asserting against them keeps all four
 * SDKs byte-identical: if this SDK's canonical form or signature ever drifts from Go's,
 * these fail rather than silently rejecting genuine webhooks in production.
 */

import { ValidationException } from '../src/exceptions';
import {
	canonicalJson,
	computeWebhookSignature,
	verifyWebhookSignature,
	extractWebhookHeaders,
	TEST_WEBHOOK_ID,
} from '../src/webhooks/verify';

const SECRET = 'whsec_test_0123456789abcdef';
const TIMESTAMP = '1700000000';

const REFERENCE_VECTORS = [
	{
		name: 'arrayOrder',
		input: '{"items":[3,1,2]}',
		canonical: '{"items":[3,1,2]}',
		signature: 'sha256=8270d9e92c09c45b1ef5b4ec50e32e2b1c3fea8a7f49947d6af0fee131854d27',
	},
	{
		name: 'emptyObj',
		input: '{}',
		canonical: '{}',
		signature: 'sha256=86e42664e55bdef9d21c29ec99ef840bb60f05f718392629bb0eb162a585147e',
	},
	{
		name: 'html',
		input: '{"url":"https://x.test/a?b=1&c=2","tag":"<b>"}',
		canonical: '{"tag":"\\u003cb\\u003e","url":"https://x.test/a?b=1\\u0026c=2"}',
		signature: 'sha256=28b274c01275f3ea7c03f3feb7fd2ec52a9594333779cae66f975d8914bc9383',
	},
	{
		name: 'nested',
		input: '{"z":{"y":1,"x":2},"a":[{"d":4,"c":3}]}',
		canonical: '{"a":[{"c":3,"d":4}],"z":{"x":2,"y":1}}',
		signature: 'sha256=710b9fed39bfd9f5c087f26f4bbb91eb5a30a56fc8e2f8e4ba41c0b92b7949a7',
	},
	{
		name: 'nulls',
		input: '{"a":null,"b":false,"c":true}',
		canonical: '{"a":null,"b":false,"c":true}',
		signature: 'sha256=2cdc9b14b681f7f80c7f4308cfe4a080840c16db5e2a2fca46e8d2a9e99677b8',
	},
	{
		name: 'numbers',
		input: '{"int":2592000,"float":9.99,"zero":0,"neg":-1.5}',
		canonical: '{"float":9.99,"int":2592000,"neg":-1.5,"zero":0}',
		signature: 'sha256=d7939b32907de3fdfb5db88092caf53aa58234e3ec62ca9813d24df4bab78d3e',
	},
	{
		name: 'realWebhook',
		input: '{"uuid":"pay@01a0c0c7","txType":"payment","status":{"status":"completed","txHash":"0xabc"},"managementPageLink":"https://qbitflow.app/m?id=1&k=2"}',
		canonical:
			'{"managementPageLink":"https://qbitflow.app/m?id=1\\u0026k=2","status":{"status":"completed","txHash":"0xabc"},"txType":"payment","uuid":"pay@01a0c0c7"}',
		signature: 'sha256=bdce3332c824b8abbe798034e6f8156d914c81c088aad6f5694df3b98241c540',
	},
	{
		name: 'simple',
		input: '{"a":1,"b":2}',
		canonical: '{"a":1,"b":2}',
		signature: 'sha256=7293f8a9be38cc10138c04b2ca50bb65533bf356f476552981079eebf7b3a53a',
	},
	{
		name: 'unicode',
		input: '{"name":"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e"}',
		canonical: '{"name":"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e"}',
		signature: 'sha256=8828459bb4f050a0ae4d633d71edefa6027c1cc39933e8b27de9bc5fafd491ac',
	},
	{
		name: 'unsorted',
		input: '{"b":2,"a":1,"c":3}',
		canonical: '{"a":1,"b":2,"c":3}',
		signature: 'sha256=cefa417c919e24dadad16670fb997f379aece68be25f46d70bd2ee6541bb7b0a',
	},
	{
		name: 'wholeFloats',
		input: '{"whole":1.0,"negWhole":-2.0,"frac":2.50}',
		canonical: '{"frac":2.5,"negWhole":-2,"whole":1}',
		signature: 'sha256=568f803efa06262d9bc43020a326a2d335739bc54c2f1f546d2f0c4d7ac70619',
	},
];

/**
 * Golden vectors generated by the Go SDK (`scratchpad/sigtest/golden`), one secret and
 * timestamp per vector. They exercise Go's exact escaping (`<>&`, U+2028/U+2029) and its
 * float64 number formatting, so a drift in either shows up here rather than in production.
 */
const GOLDEN_VECTORS = [
	{
		name: 'empty_object',
		payload: '{}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical: '{}',
		signature: 'sha256=122d17b8a94e9170db2d91edb1a4060a1847a8de8020e3a1a20ea84293f28d22',
	},
	{
		name: 'key_order_and_types',
		payload:
			'{"zeta":1,"alpha":"a","Beta":true,"nested":{"y":null,"x":[1,2,{"b":"B","a":"A"}]},"émoji":"☕"}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"Beta":true,"alpha":"a","nested":{"x":[1,2,{"a":"A","b":"B"}],"y":null},"zeta":1,"émoji":"☕"}',
		signature: 'sha256=078c8862e2a4b67245ff3c04405d313c1815d19e3f246446583919260df7332d',
	},
	{
		name: 'html_and_unicode_escaping',
		payload:
			'{"msg":"<b>ok</b> & done / fine \\"q\\" \\\\ back","line":"a b c\\ttab\\nnl","dq":"<script>"}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"dq":"\\u003cscript\\u003e","line":"a\\u2028b\\u2029c\\ttab\\nnl","msg":"\\u003cb\\u003eok\\u003c/b\\u003e \\u0026 done / fine \\"q\\" \\\\ back"}',
		signature: 'sha256=220a10812e56a3cd202440cdbe7fa255515979760c4d15f821b3a6fea34564a4',
	},
	{
		name: 'numbers_float64_semantics',
		payload:
			'{"n":[1e-7,1e-6,0.00001234,0.0001234,0.001,1e15,1e16,1e20,1e21,1.5e22,123456789.123,0.1,100.0,10.5,0,5e-324,1.7976931348623157e308,9007199254740993,2.5e-5,1234567890123456789,19.99,-5]}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"n":[1e-7,0.000001,0.00001234,0.0001234,0.001,1000000000000000,10000000000000000,100000000000000000000,1e+21,1.5e+22,123456789.123,0.1,100,10.5,0,5e-324,1.7976931348623157e+308,9007199254740992,0.000025,1234567890123456800,19.99,-5]}',
		signature: 'sha256=2969a1f1c606f2cefbc8dadef939ccf2337d0388827819c888137454deec56b8',
	},
	{
		name: 'empty_containers',
		payload: '{"emptyObj":{},"emptyArr":[],"list":[{},[],[[]],[{}]],"s":""}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical: '{"emptyArr":[],"emptyObj":{},"list":[{},[],[[]],[{}]],"s":""}',
		signature: 'sha256=de1584470053d814ee8903db86fbe07517e13a0282c1e682587ed77659f9231a',
	},
	{
		name: 'transaction_webhook',
		payload:
			'{"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695","txType":"payment","status":{"status":"completed","txHash":"0x9f2c","settlementDetails":{"feeBps":100,"txMetadata":{"networkFees":{"amount":"21000","unitsConsumed":21000},"blockData":{"number":"1234567","timestamp":1758539990},"mainCurrencyPriceUSD":0.00001234},"txAmounts":{"usd":{"platform":0.2,"merchant":19.79},"minUnits":{"platform":"200000","organization":"0","referral":"0","merchant":"19790000"}}}},"session":{"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695","reference":"ORD/2026/17","productId":42,"productName":"Café Premium","description":"Best <coffee> & tea","price":19.99,"successUrl":"https://shop.example.com/ok?o=17&x=1","organizationId":7,"organizationName":"Acme","feeBps":100,"userId":0,"test":false,"customerUUID":"3f2b1c1e-8d1a-4c2b-9b0e-1a2b3c4d5e6f","txType":"payment","availableCurrencies":[1,2,3]},"managementPageLink":"https://app.qbitflow.app/m/abc"}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"managementPageLink":"https://app.qbitflow.app/m/abc","session":{"availableCurrencies":[1,2,3],"customerUUID":"3f2b1c1e-8d1a-4c2b-9b0e-1a2b3c4d5e6f","description":"Best \\u003ccoffee\\u003e \\u0026 tea","feeBps":100,"organizationId":7,"organizationName":"Acme","price":19.99,"productId":42,"productName":"Café Premium","reference":"ORD/2026/17","successUrl":"https://shop.example.com/ok?o=17\\u0026x=1","test":false,"txType":"payment","userId":0,"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695"},"status":{"settlementDetails":{"feeBps":100,"txAmounts":{"minUnits":{"merchant":"19790000","organization":"0","platform":"200000","referral":"0"},"usd":{"merchant":19.79,"platform":0.2}},"txMetadata":{"blockData":{"number":"1234567","timestamp":1758539990},"mainCurrencyPriceUSD":0.00001234,"networkFees":{"amount":"21000","unitsConsumed":21000}}},"status":"completed","txHash":"0x9f2c"},"txType":"payment","uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695"}',
		signature: 'sha256=c6e845486a0c5d2b9f3d1fca4a9c4190649ed46b06db74d71bd2703358a411ec',
	},
	{
		name: 'subscription_billing_webhook',
		payload:
			'{"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","subscriptionReference":"plan-pro","type":"billing","data":{"uuid":"sub-hist@01a0c5be-0000-7000-8000-000000000002","createdAt":"2026-09-21T22:02:09.986381+02:00","from":"0xfrom","to":"0xto","amount":9.99,"amountMinUnits":"9990000","currencyId":2,"test":true,"transactionHash":"0xhash","organizationId":7,"userId":3,"name":"Pro","description":"Monthly","productId":9,"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","metadata":{"feeBps":100,"txMetadata":{"networkFees":{"amount":"0","unitsConsumed":0},"blockData":{"number":"","timestamp":0}},"txAmounts":{"usd":{"platform":0.0999,"merchant":9.8901},"minUnits":{"platform":"99900","organization":"0","referral":"0","merchant":"9890100"}}}}}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"data":{"amount":9.99,"amountMinUnits":"9990000","createdAt":"2026-09-21T22:02:09.986381+02:00","currencyId":2,"description":"Monthly","from":"0xfrom","metadata":{"feeBps":100,"txAmounts":{"minUnits":{"merchant":"9890100","organization":"0","platform":"99900","referral":"0"},"usd":{"merchant":9.8901,"platform":0.0999}},"txMetadata":{"blockData":{"number":"","timestamp":0},"networkFees":{"amount":"0","unitsConsumed":0}}},"name":"Pro","organizationId":7,"productId":9,"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","test":true,"to":"0xto","transactionHash":"0xhash","userId":3,"uuid":"sub-hist@01a0c5be-0000-7000-8000-000000000002"},"subscriptionReference":"plan-pro","subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","type":"billing"}',
		signature: 'sha256=c69da12a34355745027c9db89877cdd8187df497171c2ee591bf7a80abd36187',
	},
	{
		name: 'status_transition_webhook',
		payload:
			'{"type":"status_transition","subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","data":{"previousStatus":"active","currentStatus":"low_on_funds","updatedAt":"2026-09-22T10:00:00Z"}}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"data":{"currentStatus":"low_on_funds","previousStatus":"active","updatedAt":"2026-09-22T10:00:00Z"},"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","type":"status_transition"}',
		signature: 'sha256=88708bfd796485695fd051a03a32ee3374ecf7b02ead27b1bbcf67504380f46a',
	},
];
/**
 * Second set of golden vectors generated by the Go SDK (`scratchpad/golden`): 19+-digit decimal
 * strings, C0 controls, lone surrogates (→ U+FFFD), `-0` and exponent forms, and keys ordered
 * by UTF-8 bytes rather than UTF-16 code units. Non-ASCII characters are written as `\u`
 * escapes so the literals are unambiguous; the values are exactly those Go produced.
 */
const GOLDEN_VECTORS_2 = [
	{
		name: 'decimal strings of 19+ digits stay strings',
		payload:
			'{"amountMinUnits":"1000000000000000000","txAmounts":{"minUnits":{"merchant":"99000000000000000000","platform":"1000000000000000000000","referral":"0"}},"big":12345678901234567890,"id":"0001","neg":"-12345678901234567890"}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"amountMinUnits":"1000000000000000000","big":12345678901234567000,"id":"0001","neg":"-12345678901234567890","txAmounts":{"minUnits":{"merchant":"99000000000000000000","platform":"1000000000000000000000","referral":"0"}}}',
		signature: 'sha256=88423199655b9f5e5db5e4b4fbdaea52d61f64f08837cad0a65bab1ea87b6a19',
	},
	{
		name: 'control characters',
		payload:
			'{"s":"a\\bb\\fc\\u0000d\\u001fe\\u007ff\\u0080g","k\\u0001":"x","tab":"\\t","cr":"\\r"}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical:
			'{"cr":"\\r","k\\u0001":"x","s":"a\\bb\\fc\\u0000d\\u001fe\u007ff\u0080g","tab":"\\t"}',
		signature: 'sha256=4118c0a289dd2e4bb4ab62ad2b13a7e1ff60981717c75d6c1ce1c4848e82d5f0',
	},
	{
		name: 'lone surrogates become U+FFFD',
		payload: '{"hi":"\\ud800x","lo":"\\udfff","pair":"\ud83d\ude00"}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical: '{"hi":"\ufffdx","lo":"\ufffd","pair":"\ud83d\ude00"}',
		signature: 'sha256=b31ca0014545f32bf62e937955fe50e11c5a6cf68f57052008edd0cfb2af29d3',
	},
	{
		name: 'negative zero and exponent forms',
		payload: '{"a":-0,"b":-0.0,"c":1E2,"d":1e-7,"e":-1.5e-10,"f":0.0,"g":-0.000001}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical: '{"a":-0,"b":-0,"c":100,"d":1e-7,"e":-1.5e-10,"f":0,"g":-0.000001}',
		signature: 'sha256=45e3033a130332ab91bce58115d670ac83a9d4a41b59f51323c4e20625bcd2bc',
	},
	{
		name: 'keys are ordered by UTF-8 bytes',
		payload: '{"\ud83d\ude00":1,"\uffff":2,"a":3,"\u00e9":4,"Z":5,"":6,"aa":7,"a\\u0000":8}',
		secret: 'whsec_golden_secret_0123456789',
		timestamp: '1758540000',
		canonical: '{"":6,"Z":5,"a":3,"a\\u0000":8,"aa":7,"\u00e9":4,"\uffff":2,"\ud83d\ude00":1}',
		signature: 'sha256=3b3885769c26eac4d862579cb4782135f5021d1ba5fa6c801d50f9228c164fb9',
	},
];
const nowTs = () => Math.floor(Date.now() / 1000).toString();

describe('Webhook signature verification', () => {
	describe('cross-SDK reference vectors (generated by the Go SDK)', () => {
		it.each(REFERENCE_VECTORS)(
			'canonicalises $name identically to Go',
			({ input, canonical }) => {
				expect(canonicalJson(input)).toBe(canonical);
			}
		);

		it.each(REFERENCE_VECTORS)('signs $name identically to Go', ({ input, signature }) => {
			expect(computeWebhookSignature(SECRET, TIMESTAMP, input)).toBe(signature);
		});
	});

	describe('golden vectors (Go-generated, per-vector secret and timestamp)', () => {
		it.each(GOLDEN_VECTORS)(
			'canonicalises $name identically to Go',
			({ payload, canonical }) => {
				expect(canonicalJson(payload)).toBe(canonical);
			}
		);

		it.each(GOLDEN_VECTORS)(
			'signs $name identically to Go',
			({ payload, secret, timestamp, signature }) => {
				expect(computeWebhookSignature(secret, timestamp, payload)).toBe(signature);
			}
		);

		it.each(GOLDEN_VECTORS)(
			'verifies $name end to end',
			({ payload, secret, timestamp, signature }) => {
				expect(() =>
					verifyWebhookSignature(secret, timestamp, signature, payload, {
						skipTimestampCheck: true,
					})
				).not.toThrow();
			}
		);
	});

	describe('golden vectors, second set (Go-generated)', () => {
		it.each(GOLDEN_VECTORS_2)(
			'canonicalises "$name" identically to Go',
			({ payload, canonical }) => {
				expect(canonicalJson(payload)).toBe(canonical);
			}
		);

		it.each(GOLDEN_VECTORS_2)(
			'signs "$name" identically to Go',
			({ payload, secret, timestamp, signature }) => {
				expect(computeWebhookSignature(secret, timestamp, payload)).toBe(signature);
				expect(() =>
					verifyWebhookSignature(secret, timestamp, signature, payload, {
						skipTimestampCheck: true,
					})
				).not.toThrow();
			}
		);

		it('produces the same canonical form from raw bytes as from the text', () => {
			for (const { payload, canonical } of GOLDEN_VECTORS_2) {
				expect(canonicalJson(Buffer.from(payload))).toBe(canonical);
				expect(canonicalJson(new TextEncoder().encode(payload))).toBe(canonical);
				expect(canonicalJson(new TextEncoder().encode(payload).buffer)).toBe(canonical);
			}
		});
	});

	describe('canonicalJson', () => {
		it('sorts object keys at every level', () => {
			expect(canonicalJson('{"b":2,"a":1}')).toBe('{"a":1,"b":2}');
			expect(canonicalJson('{"z":{"y":1,"x":2}}')).toBe('{"z":{"x":2,"y":1}}');
		});

		it('preserves array order', () => {
			// Arrays are ordered by definition: sorting them would change meaning.
			expect(canonicalJson('{"items":[3,1,2]}')).toBe('{"items":[3,1,2]}');
		});

		it('drops insignificant whitespace', () => {
			expect(canonicalJson('{\n  "a" : 1 }')).toBe('{"a":1}');
		});

		it('accepts a Buffer, a Uint8Array, an ArrayBuffer, a string, or a parsed object', () => {
			const expected = '{"a":1,"b":2}';
			expect(canonicalJson('{"b":2,"a":1}')).toBe(expected);
			expect(canonicalJson(Buffer.from('{"b":2,"a":1}'))).toBe(expected);
			expect(canonicalJson(new TextEncoder().encode('{"b":2,"a":1}'))).toBe(expected);
			expect(canonicalJson(new TextEncoder().encode('{"b":2,"a":1}').buffer)).toBe(expected);
			expect(canonicalJson({ b: 2, a: 1 })).toBe(expected);
		});

		it('keeps -0 and {} / [] from an already-parsed object, and honours toJSON', () => {
			expect(canonicalJson({ n: -0, o: {}, a: [], d: new Date(0), u: undefined })).toBe(
				'{"a":[],"d":"1970-01-01T00:00:00.000Z","n":-0,"o":{}}'
			);
			expect(canonicalJson(JSON.parse('{"n":-0.0}'))).toBe('{"n":-0}');
		});

		it('rejects invalid JSON, missing payloads and values JSON cannot represent', () => {
			expect(() => canonicalJson('{not json')).toThrow(ValidationException);
			expect(() => canonicalJson(null)).toThrow(ValidationException);
			expect(() => canonicalJson(undefined)).toThrow(ValidationException);
			expect(() => canonicalJson({ n: NaN })).toThrow(ValidationException);
			expect(() => canonicalJson({ n: 1n })).toThrow(ValidationException);
			const circular: Record<string, unknown> = {};
			circular.self = circular;
			expect(() => canonicalJson(circular)).toThrow(ValidationException);
		});
	});

	describe('verifyWebhookSignature', () => {
		const payload = '{"uuid":"pay@abc","txType":"payment"}';

		it('accepts a genuine webhook', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			expect(() => verifyWebhookSignature(SECRET, ts, sig, payload)).not.toThrow();
		});

		it('accepts a payload whose keys were reordered in transit', () => {
			// The whole point of canonicalisation.
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, '{"a":1,"b":2}');
			expect(() => verifyWebhookSignature(SECRET, ts, sig, '{"b":2,"a":1}')).not.toThrow();
		});

		it('rejects a tampered payload', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			expect(() =>
				verifyWebhookSignature(SECRET, ts, sig, '{"uuid":"pay@EVIL","txType":"payment"}')
			).toThrow('signature mismatch');
		});

		it('rejects a tampered timestamp', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			const other = (Number(ts) - 30).toString();
			expect(() => verifyWebhookSignature(SECRET, other, sig, payload)).toThrow(
				'signature mismatch'
			);
		});

		it('rejects the wrong secret', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			expect(() => verifyWebhookSignature('whsec_wrong', ts, sig, payload)).toThrow(
				'signature mismatch'
			);
		});

		it('rejects a replayed webhook outside the window', () => {
			const old = (Math.floor(Date.now() / 1000) - 600).toString();
			const sig = computeWebhookSignature(SECRET, old, payload);
			expect(() => verifyWebhookSignature(SECRET, old, sig, payload)).toThrow('expired');
		});

		it('rejects a timestamp too far in the future', () => {
			// Guards against a forged future timestamp extending the replay window.
			const future = (Math.floor(Date.now() / 1000) + 600).toString();
			const sig = computeWebhookSignature(SECRET, future, payload);
			expect(() => verifyWebhookSignature(SECRET, future, sig, payload)).toThrow('expired');
		});

		it('honours a custom replay window', () => {
			const old = (Math.floor(Date.now() / 1000) - 600).toString();
			const sig = computeWebhookSignature(SECRET, old, payload);
			expect(() =>
				verifyWebhookSignature(SECRET, old, sig, payload, { maxTimestampAgeSeconds: 1800 })
			).not.toThrow();
		});

		it('parses the timestamp like Go strconv.ParseInt', () => {
			const now = Math.floor(Date.now() / 1000);
			const plus = `+${now}`;
			const sig = computeWebhookSignature(SECRET, plus, payload);
			expect(() => verifyWebhookSignature(SECRET, plus, sig, payload)).not.toThrow();
			for (const bad of ['nope', ` ${now}`, `${now} `, '1e9', '12.5', '0x10', '', '١٢']) {
				expect(() => verifyWebhookSignature(SECRET, bad, 'sha256=abc', payload)).toThrow(
					ValidationException
				);
			}
			// Outside the int64 range Go rejects the value outright.
			expect(() =>
				verifyWebhookSignature(SECRET, '9223372036854775808', 'sha256=abc', payload)
			).toThrow('out of range');
			// Extreme but valid values cannot overflow into the window.
			expect(() =>
				verifyWebhookSignature(SECRET, '-9223372036854775808', 'sha256=abc', payload)
			).toThrow('expired');
		});

		it('treats a replay window <= 0 as the default (300 s)', () => {
			const old = (Math.floor(Date.now() / 1000) - 200).toString();
			const tooOld = (Math.floor(Date.now() / 1000) - 400).toString();
			const sigOld = computeWebhookSignature(SECRET, old, payload);
			const sigTooOld = computeWebhookSignature(SECRET, tooOld, payload);
			for (const maxTimestampAgeSeconds of [0, -5]) {
				expect(() =>
					verifyWebhookSignature(SECRET, old, sigOld, payload, { maxTimestampAgeSeconds })
				).not.toThrow();
				expect(() =>
					verifyWebhookSignature(SECRET, tooOld, sigTooOld, payload, {
						maxTimestampAgeSeconds,
					})
				).toThrow('expired');
			}
		});

		it('rejects empty or malformed signatures', () => {
			const ts = nowTs();
			for (const bad of ['', 'sha256=', 'deadbeef', 'sha512=abc']) {
				expect(() => verifyWebhookSignature(SECRET, ts, bad, payload)).toThrow();
			}
		});
	});

	describe('extractWebhookHeaders', () => {
		it('reads a plain Node headers object case-insensitively', () => {
			const h = extractWebhookHeaders({
				'x-webhook-signature-256': 'sha256=abc',
				'X-Webhook-Timestamp': '1700000000',
				'x-webhook-id': 'pay@abc',
			});
			expect(h.signature).toBe('sha256=abc');
			expect(h.timestamp).toBe('1700000000');
			expect(h.webhookId).toBe('pay@abc');
			expect(h.isTest).toBe(false);
		});

		it('reads a Fetch API Headers instance', () => {
			const h = extractWebhookHeaders(
				new Headers({
					'X-Webhook-Signature-256': 'sha256=abc',
					'X-Webhook-Timestamp': '1700000000',
					'X-Webhook-Id': TEST_WEBHOOK_ID,
				})
			);
			expect(h.signature).toBe('sha256=abc');
			expect(h.isTest).toBe(true);
		});

		it('takes the first value when a header repeats', () => {
			const h = extractWebhookHeaders({
				'x-webhook-timestamp': ['1700000000', '1700000001'],
			});
			expect(h.timestamp).toBe('1700000000');
		});

		it('returns empty strings for missing headers', () => {
			const h = extractWebhookHeaders({});
			expect(h.signature).toBe('');
			expect(h.timestamp).toBe('');
			expect(h.isTest).toBe(false);
		});
	});
});
