/**
 * Local webhook signature verification.
 *
 * The REFERENCE_VECTORS below were generated by the Go SDK, which canonicalises with the
 * same `encoding/json` the QBitFlow API itself uses. Asserting against them keeps all four
 * SDKs byte-identical: if this SDK's canonical form or signature ever drifts from Go's,
 * these fail rather than silently rejecting genuine webhooks in production.
 */

import {
	canonicalJson,
	computeWebhookSignature,
	verifyWebhookSignature,
	extractWebhookHeaders,
	TEST_WEBHOOK_ID,
} from '../src/webhooks/verify';

const SECRET = "whsec_test_0123456789abcdef";
const TIMESTAMP = "1700000000";

const REFERENCE_VECTORS = [
	{
		name: "arrayOrder",
		input: "{\"items\":[3,1,2]}",
		canonical: "{\"items\":[3,1,2]}",
		signature: "sha256=8270d9e92c09c45b1ef5b4ec50e32e2b1c3fea8a7f49947d6af0fee131854d27",
	},
	{
		name: "emptyObj",
		input: "{}",
		canonical: "{}",
		signature: "sha256=86e42664e55bdef9d21c29ec99ef840bb60f05f718392629bb0eb162a585147e",
	},
	{
		name: "html",
		input: "{\"url\":\"https://x.test/a?b=1&c=2\",\"tag\":\"<b>\"}",
		canonical: "{\"tag\":\"\\u003cb\\u003e\",\"url\":\"https://x.test/a?b=1\\u0026c=2\"}",
		signature: "sha256=28b274c01275f3ea7c03f3feb7fd2ec52a9594333779cae66f975d8914bc9383",
	},
	{
		name: "nested",
		input: "{\"z\":{\"y\":1,\"x\":2},\"a\":[{\"d\":4,\"c\":3}]}",
		canonical: "{\"a\":[{\"c\":3,\"d\":4}],\"z\":{\"x\":2,\"y\":1}}",
		signature: "sha256=710b9fed39bfd9f5c087f26f4bbb91eb5a30a56fc8e2f8e4ba41c0b92b7949a7",
	},
	{
		name: "nulls",
		input: "{\"a\":null,\"b\":false,\"c\":true}",
		canonical: "{\"a\":null,\"b\":false,\"c\":true}",
		signature: "sha256=2cdc9b14b681f7f80c7f4308cfe4a080840c16db5e2a2fca46e8d2a9e99677b8",
	},
	{
		name: "numbers",
		input: "{\"int\":2592000,\"float\":9.99,\"zero\":0,\"neg\":-1.5}",
		canonical: "{\"float\":9.99,\"int\":2592000,\"neg\":-1.5,\"zero\":0}",
		signature: "sha256=d7939b32907de3fdfb5db88092caf53aa58234e3ec62ca9813d24df4bab78d3e",
	},
	{
		name: "realWebhook",
		input: "{\"uuid\":\"pay@01a0c0c7\",\"txType\":\"payment\",\"status\":{\"status\":\"completed\",\"txHash\":\"0xabc\"},\"managementPageLink\":\"https://qbitflow.app/m?id=1&k=2\"}",
		canonical: "{\"managementPageLink\":\"https://qbitflow.app/m?id=1\\u0026k=2\",\"status\":{\"status\":\"completed\",\"txHash\":\"0xabc\"},\"txType\":\"payment\",\"uuid\":\"pay@01a0c0c7\"}",
		signature: "sha256=bdce3332c824b8abbe798034e6f8156d914c81c088aad6f5694df3b98241c540",
	},
	{
		name: "simple",
		input: "{\"a\":1,\"b\":2}",
		canonical: "{\"a\":1,\"b\":2}",
		signature: "sha256=7293f8a9be38cc10138c04b2ca50bb65533bf356f476552981079eebf7b3a53a",
	},
	{
		name: "unicode",
		input: "{\"name\":\"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e\"}",
		canonical: "{\"name\":\"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e\"}",
		signature: "sha256=8828459bb4f050a0ae4d633d71edefa6027c1cc39933e8b27de9bc5fafd491ac",
	},
	{
		name: "unsorted",
		input: "{\"b\":2,\"a\":1,\"c\":3}",
		canonical: "{\"a\":1,\"b\":2,\"c\":3}",
		signature: "sha256=cefa417c919e24dadad16670fb997f379aece68be25f46d70bd2ee6541bb7b0a",
	},
	{
		name: "wholeFloats",
		input: "{\"whole\":1.0,\"negWhole\":-2.0,\"frac\":2.50}",
		canonical: "{\"frac\":2.5,\"negWhole\":-2,\"whole\":1}",
		signature: "sha256=568f803efa06262d9bc43020a326a2d335739bc54c2f1f546d2f0c4d7ac70619",
	},
];

const nowTs = () => Math.floor(Date.now() / 1000).toString();

describe('Webhook signature verification', () => {
	describe('cross-SDK reference vectors (generated by the Go SDK)', () => {
		it.each(REFERENCE_VECTORS)('canonicalises $name identically to Go', ({ input, canonical }) => {
			expect(canonicalJson(input)).toBe(canonical);
		});

		it.each(REFERENCE_VECTORS)('signs $name identically to Go', ({ input, signature }) => {
			expect(computeWebhookSignature(SECRET, TIMESTAMP, input)).toBe(signature);
		});
	});

	describe('canonicalJson', () => {
		it('sorts object keys at every level', () => {
			expect(canonicalJson('{"b":2,"a":1}')).toBe('{"a":1,"b":2}');
			expect(canonicalJson('{"z":{"y":1,"x":2}}')).toBe('{"z":{"x":2,"y":1}}');
		});

		it('preserves array order', () => {
			// Arrays are ordered by definition: sorting them would change meaning.
			expect(canonicalJson('{"items":[3,1,2]}')).toBe('{"items":[3,1,2]}');
		});

		it('drops insignificant whitespace', () => {
			expect(canonicalJson('{\n  "a" : 1 }')).toBe('{"a":1}');
		});

		it('accepts a Buffer, a string, or a parsed object', () => {
			const expected = '{"a":1,"b":2}';
			expect(canonicalJson('{"b":2,"a":1}')).toBe(expected);
			expect(canonicalJson(Buffer.from('{"b":2,"a":1}'))).toBe(expected);
			expect(canonicalJson({ b: 2, a: 1 })).toBe(expected);
		});

		it('rejects invalid JSON and missing payloads', () => {
			expect(() => canonicalJson('{not json')).toThrow();
			expect(() => canonicalJson(null)).toThrow();
			expect(() => canonicalJson(undefined)).toThrow();
		});
	});

	describe('verifyWebhookSignature', () => {
		const payload = '{"uuid":"pay@abc","txType":"payment"}';

		it('accepts a genuine webhook', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			expect(() => verifyWebhookSignature(SECRET, ts, sig, payload)).not.toThrow();
		});

		it('accepts a payload whose keys were reordered in transit', () => {
			// The whole point of canonicalisation.
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, '{"a":1,"b":2}');
			expect(() => verifyWebhookSignature(SECRET, ts, sig, '{"b":2,"a":1}')).not.toThrow();
		});

		it('rejects a tampered payload', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			expect(() =>
				verifyWebhookSignature(SECRET, ts, sig, '{"uuid":"pay@EVIL","txType":"payment"}')
			).toThrow('signature mismatch');
		});

		it('rejects a tampered timestamp', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			const other = (Number(ts) - 30).toString();
			expect(() => verifyWebhookSignature(SECRET, other, sig, payload)).toThrow('signature mismatch');
		});

		it('rejects the wrong secret', () => {
			const ts = nowTs();
			const sig = computeWebhookSignature(SECRET, ts, payload);
			expect(() => verifyWebhookSignature('whsec_wrong', ts, sig, payload)).toThrow('signature mismatch');
		});

		it('rejects a replayed webhook outside the window', () => {
			const old = (Math.floor(Date.now() / 1000) - 600).toString();
			const sig = computeWebhookSignature(SECRET, old, payload);
			expect(() => verifyWebhookSignature(SECRET, old, sig, payload)).toThrow('expired');
		});

		it('rejects a timestamp too far in the future', () => {
			// Guards against a forged future timestamp extending the replay window.
			const future = (Math.floor(Date.now() / 1000) + 600).toString();
			const sig = computeWebhookSignature(SECRET, future, payload);
			expect(() => verifyWebhookSignature(SECRET, future, sig, payload)).toThrow('expired');
		});

		it('honours a custom replay window', () => {
			const old = (Math.floor(Date.now() / 1000) - 600).toString();
			const sig = computeWebhookSignature(SECRET, old, payload);
			expect(() =>
				verifyWebhookSignature(SECRET, old, sig, payload, { maxTimestampAgeSeconds: 1800 })
			).not.toThrow();
		});

		it('rejects a non-numeric timestamp', () => {
			expect(() => verifyWebhookSignature(SECRET, 'nope', 'sha256=abc', payload)).toThrow();
		});

		it('rejects empty or malformed signatures', () => {
			const ts = nowTs();
			for (const bad of ['', 'sha256=', 'deadbeef', 'sha512=abc']) {
				expect(() => verifyWebhookSignature(SECRET, ts, bad, payload)).toThrow();
			}
		});
	});

	describe('extractWebhookHeaders', () => {
		it('reads a plain Node headers object case-insensitively', () => {
			const h = extractWebhookHeaders({
				'x-webhook-signature-256': 'sha256=abc',
				'X-Webhook-Timestamp': '1700000000',
				'x-webhook-id': 'pay@abc',
			});
			expect(h.signature).toBe('sha256=abc');
			expect(h.timestamp).toBe('1700000000');
			expect(h.webhookId).toBe('pay@abc');
			expect(h.isTest).toBe(false);
		});

		it('reads a Fetch API Headers instance', () => {
			const h = extractWebhookHeaders(
				new Headers({
					'X-Webhook-Signature-256': 'sha256=abc',
					'X-Webhook-Timestamp': '1700000000',
					'X-Webhook-Id': TEST_WEBHOOK_ID,
				})
			);
			expect(h.signature).toBe('sha256=abc');
			expect(h.isTest).toBe(true);
		});

		it('takes the first value when a header repeats', () => {
			const h = extractWebhookHeaders({ 'x-webhook-timestamp': ['1700000000', '1700000001'] });
			expect(h.timestamp).toBe('1700000000');
		});

		it('returns empty strings for missing headers', () => {
			const h = extractWebhookHeaders({});
			expect(h.signature).toBe('');
			expect(h.timestamp).toBe('');
			expect(h.isTest).toBe(false);
		});
	});
});
